# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Prviders_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Prviders_groupBox.setMinimumSize(QtCore.QSize(802, 430))
        self.Prviders_groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Prviders_groupBox.setObjectName("Prviders_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Prviders_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.av_label = QtWidgets.QLabel(self.Prviders_groupBox)
        self.av_label.setAlignment(QtCore.Qt.AlignCenter)
        self.av_label.setObjectName("av_label")
        self.gridLayout_2.addWidget(self.av_label, 0, 0, 1, 1)
        self.fw_label = QtWidgets.QLabel(self.Prviders_groupBox)
        self.fw_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fw_label.setObjectName("fw_label")
        self.gridLayout_2.addWidget(self.fw_label, 0, 1, 1, 1)
        self.wp_label = QtWidgets.QLabel(self.Prviders_groupBox)
        self.wp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wp_label.setObjectName("wp_label")
        self.gridLayout_2.addWidget(self.wp_label, 0, 2, 1, 2)
        self.av_textBrowser = QtWidgets.QTextBrowser(self.Prviders_groupBox)
        self.av_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.av_textBrowser.setObjectName("av_textBrowser")
        self.gridLayout_2.addWidget(self.av_textBrowser, 1, 0, 1, 1)
        self.fw_textBrowser = QtWidgets.QTextBrowser(self.Prviders_groupBox)
        self.fw_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fw_textBrowser.setObjectName("fw_textBrowser")
        self.gridLayout_2.addWidget(self.fw_textBrowser, 1, 1, 1, 1)
        self.wp_textBrowser = QtWidgets.QTextBrowser(self.Prviders_groupBox)
        self.wp_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wp_textBrowser.setObjectName("wp_textBrowser")
        self.gridLayout_2.addWidget(self.wp_textBrowser, 1, 2, 1, 2)
        self.Settings_groupBox = QtWidgets.QGroupBox(self.Prviders_groupBox)
        self.Settings_groupBox.setObjectName("Settings_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Settings_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.settings_textBrowser = QtWidgets.QTextBrowser(self.Settings_groupBox)
        self.settings_textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.settings_textBrowser.setObjectName("settings_textBrowser")
        self.gridLayout_4.addWidget(self.settings_textBrowser, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.Settings_groupBox, 2, 0, 1, 4)
        self.version_groupBox = QtWidgets.QGroupBox(self.Prviders_groupBox)
        self.version_groupBox.setMinimumSize(QtCore.QSize(778, 71))
        self.version_groupBox.setObjectName("version_groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.version_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.version_textBrowser = QtWidgets.QTextBrowser(self.version_groupBox)
        self.version_textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.version_textBrowser.setObjectName("version_textBrowser")
        self.gridLayout_5.addWidget(self.version_textBrowser, 0, 0, 2, 1)
        self.gridLayout_2.addWidget(self.version_groupBox, 3, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(657, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 3)
        self.status_pushButton = QtWidgets.QPushButton(self.Prviders_groupBox)
        self.status_pushButton.setMinimumSize(QtCore.QSize(111, 31))
        self.status_pushButton.setMaximumSize(QtCore.QSize(111, 31))
        self.status_pushButton.setObjectName("status_pushButton")
        self.gridLayout_2.addWidget(self.status_pushButton, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.Prviders_groupBox, 0, 0, 1, 1)
        self.Scan_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Scan_groupBox.setMinimumSize(QtCore.QSize(0, 141))
        self.Scan_groupBox.setObjectName("Scan_groupBox")
        self.QS_radioButton = QtWidgets.QRadioButton(self.Scan_groupBox)
        self.QS_radioButton.setGeometry(QtCore.QRect(12, 70, 90, 20))
        self.QS_radioButton.setChecked(True)
        self.QS_radioButton.setObjectName("QS_radioButton")
        self.FS_radioButton = QtWidgets.QRadioButton(self.Scan_groupBox)
        self.FS_radioButton.setGeometry(QtCore.QRect(12, 90, 79, 20))
        self.FS_radioButton.setObjectName("FS_radioButton")
        self.CS_radioButton = QtWidgets.QRadioButton(self.Scan_groupBox)
        self.CS_radioButton.setGeometry(QtCore.QRect(12, 114, 102, 20))
        self.CS_radioButton.setObjectName("CS_radioButton")
        self.path_lineEdit = QtWidgets.QLineEdit(self.Scan_groupBox)
        self.path_lineEdit.setGeometry(QtCore.QRect(121, 112, 371, 24))
        self.path_lineEdit.setReadOnly(True)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.path_pushButton = QtWidgets.QPushButton(self.Scan_groupBox)
        self.path_pushButton.setGeometry(QtCore.QRect(497, 110, 93, 28))
        self.path_pushButton.setObjectName("path_pushButton")
        self.start_pushButton = QtWidgets.QPushButton(self.Scan_groupBox)
        self.start_pushButton.setGeometry(QtCore.QRect(597, 110, 93, 28))
        self.start_pushButton.setObjectName("start_pushButton")
        self.stop_pushButton = QtWidgets.QPushButton(self.Scan_groupBox)
        self.stop_pushButton.setEnabled(False)
        self.stop_pushButton.setGeometry(QtCore.QRect(697, 110, 93, 28))
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.Scan_groupBox)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 771, 51))
        self.groupBox.setMinimumSize(QtCore.QSize(771, 51))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 51))
        self.groupBox.setObjectName("groupBox")
        self.update_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.update_pushButton.setGeometry(QtCore.QRect(220, 13, 93, 28))
        self.update_pushButton.setObjectName("update_pushButton")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 211, 16))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.Scan_groupBox, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Windows Security Helper Tool"))
        self.Prviders_groupBox.setTitle(_translate("MainWindow", "Security Status"))
        self.av_label.setText(_translate("MainWindow", "Antivirus"))
        self.fw_label.setText(_translate("MainWindow", "Firewall"))
        self.wp_label.setText(_translate("MainWindow", "Web Protection"))
        self.av_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.fw_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.wp_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Settings_groupBox.setTitle(_translate("MainWindow", "Virus and Threat Protection Settings"))
        self.settings_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.version_groupBox.setTitle(_translate("MainWindow", "Modules Version"))
        self.version_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.status_pushButton.setText(_translate("MainWindow", "Get Latest Status"))
        self.Scan_groupBox.setTitle(_translate("MainWindow", "Actions"))
        self.QS_radioButton.setText(_translate("MainWindow", "Quick Scan"))
        self.FS_radioButton.setText(_translate("MainWindow", "Full Scan"))
        self.CS_radioButton.setText(_translate("MainWindow", "Custom Scan"))
        self.path_pushButton.setText(_translate("MainWindow", "Choose Path"))
        self.start_pushButton.setText(_translate("MainWindow", "Start"))
        self.stop_pushButton.setText(_translate("MainWindow", "Stop"))
        self.groupBox.setTitle(_translate("MainWindow", "Update"))
        self.update_pushButton.setText(_translate("MainWindow", "Update"))
        self.label.setText(_translate("MainWindow", "Update Windows Defender Modules"))
